# netlify.toml - Arquivo de Configuração Essencial e Corrigido

[build]
  # Comando para dizer ao Netlify para usar o Eleventy para construir o site.
  command = "eleventy"
  # Esta é a correção final: Aponta para a pasta correta onde o site pronto está.
  publish = "_site"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Regra de cache para acelerar o carregamento de imagens
[[headers]]
  for = "/imagens/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
