# netlify.toml - Arquivo de Configuração Essencial

[build]
  # Esta linha informa ao Netlify que a pasta principal do seu site 
  # é a raiz do repositório, onde estão o index.html e o style.css.
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Regra de cache para acelerar o carregamento de imagens
[[headers]]
  for = "/imagens/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
