# ===================================================================
# PAINEL DE COMANDO v5.0 - O ESPELHO DA REVISTA DIGITAL
# Criado para ser 100% intuitivo para a Chef Maria Conceição
# ===================================================================

# --- Conexão e Configurações Base ---
backend:
  name: git-gateway
  branch: desenvolvimento
media_folder: "imagens/uploads"
public_folder: "/imagens/uploads"
locale: 'pt'
publish_mode: editorial_workflow

# ===================================================================
# COLEÇÕES DE CONTEÚDO
# Cada coleção representa uma área editável do site.
# ===================================================================
collections:
  # --- 1. PÁGINAS PRINCIPAIS ---
  - name: "paginas"
    label: "📄 Páginas Principais do Site"
    description: "Altere aqui os textos das páginas mais importantes como a Página Inicial, ChefBox, FAQ, etc."
    files:
      - label: "Página Inicial"
        name: "home"
        file: "index.md"
        fields:
          - { label: "Secção Topo - Título", name: "hero_titulo", widget: "string" }
          - { label: "Secção Topo - Subtítulo", name: "hero_subtitulo", widget: "text" }
          - { label: "Secção Catálogo - Título", name: "catalogo_titulo", widget: "string", default: "Nosso Catálogo Inteligente" }
          - { label: "Secção Catálogo - Subtítulo", name: "catalogo_subtitulo", widget: "text" }
          - { label: "Secção Novidades - Título", name: "novidades_titulo", widget: "string", default: "Novidades na Revista" }

      - label: "Página 'Comida de Verdade' (Sobre)"
        name: "sobre"
        file: "comida-de-verdade/index.md"
        fields:
          - { label: "Título da Página", name: "title", widget: "string" }
          - { label: "Conteúdo da Página", name: "body", widget: "markdown" }

      - label: "Página 'ChefBox'"
        name: "chefbox"
        file: "chefbox/index.md" # ATENÇÃO: Confirme se este é o caminho do ficheiro
        fields:
          - { label: "Título da Página", name: "title", widget: "string" }
          - { label: "Conteúdo da Página", name: "body", widget: "markdown" }

      - label: "Página 'Chefbrico Club'"
        name: "club"
        file: "chefbrico-club/index.md" # ATENÇÃO: Confirme se este é o caminho do ficheiro
        fields:
          - { label: "Título da Página", name: "title", widget: "string" }
          - { label: "Conteúdo da Página", name: "body", widget: "markdown" }

      - label: "Página 'Onde Encontrar' (Textos e Títulos)"
        name: "onde_encontrar_main"
        file: "onde-encontrar/index.md"
        fields:
          - { label: "Título Principal da Página", name: "title", widget: "string" }
          - { label: "Título da Secção 'Plano Piloto'", name: "titulo_plano_piloto", widget: "string" }
          - { label: "Título da Secção 'Brasília'", name: "titulo_brasilia", widget: "string" }
          - { label: "Título da Secção 'Próximo a Brasília'", name: "titulo_proximo", widget: "string" }
          - { label: "Texto Final (Pontos de Referência)", name: "texto_final", widget: "text" }
          
      - label: "Página de 'Perguntas Frequentes' (FAQ)"
        name: "faq"
        file: "faq/index.md"
        fields:
          - { label: "Título da Página", name: "title", widget: "string", default: "Perguntas Frequentes" }
          - { label: "Subtítulo da Página", name: "subtitle", widget: "text" }
          - label: "Grupo de Perguntas: 'Porque Comprar da ChefBrico'"
            name: "faq_grupo_1"
            widget: "list"
            fields:
              - { label: "Pergunta", name: "pergunta", widget: "string" }
              - { label: "Resposta", name: "resposta", widget: "markdown" }
          - label: "Grupo de Perguntas: 'Como Comprar na Loja ChefBrico'"
            name: "faq_grupo_2"
            widget: "list"
            fields:
              - { label: "Pergunta", name: "pergunta", widget: "string" }
              - { label: "Resposta", name: "resposta", widget: "markdown" }

  # --- 2. RECEITAS ---
  - name: "receitas"
    label: "🍳 Receitas do Cardápio"
    # ... (o resto da coleção de receitas continua igual, pois já estava bem detalhada)

  # --- 3. BLOG ---
  - name: "blog"
    label: "✍️ Blog da Chef"
    # ... (o resto da coleção do blog continua igual)

  # --- 4. BAIRROS/LOCAIS ---
  - name: "locais"
    label: "📍 Bairros (para a pág. Onde Encontrar)"
    description: "Adicione ou edite os BAIRROS INDIVIDUAIS que aparecerão como botões na página 'Onde Encontrar'."
    # ... (o resto da coleção de locais continua igual)

  # --- 5. CONFIGURAÇÕES GERAIS ---
  - name: "settings"
    label: "⚙️ Configurações Gerais do Site"
    # ... (o resto da coleção de configurações continua igual)
