# Backend: Ligação direta com o GitHub
backend:
  name: github
  repo: ChefBrico/chefbrico-hub-de-autoridade # O seu repositório
  branch: desenvolvimento # O seu ramo

# Media e Coleções continuam iguais
media_folder: "imagens/uploads"
public_folder: "/imagens/uploads"

collections:
  - name: "paginas_principais"
    label: "Páginas Principais"
    files:
      - file: "index.html"
        label: "Página Inicial (Homepage)"
        name: "homepage"
        fields:
          - { label: "Título (SEO)", name: "title", widget: "string" }
          - { label: "Descrição (SEO)", name: "description", widget: "string" }
          - { label: "Conteúdo da Página", name: "body", widget: "markdown" }
      - file: "comida-de-verdade/index.html"
        label: "Página 'Comida de Verdade'"
        name: "comida_de_verdade"
        fields:
          - { label: "Título (SEO)", name: "title", widget: "string" }
          - { label: "Descrição (SEO)", name: "description", widget: "string" }
          - { label: "Conteúdo da Página", name: "body", widget: "markdown" }
      - file: "onde-encontrar/index.html"
        label: "Página Principal 'Onde Encontrar'"
        name: "onde_encontrar_hub"
        fields:
          - { label: "Título (SEO)", name: "title", widget: "string" }
          - { label: "Descrição (SEO)", name: "description", widget: "string" }
          - { label: "Conteúdo da Página", name: "body", widget: "markdown" }
      - file: "receitas/index.html"
        label: "Página do Catálogo de Receitas"
        name: "catalogo_receitas"
        fields:
          - { label: "Título (SEO)", name: "title", widget: "string" }
          - { label: "Descrição (SEO)", name: "description", widget: "string" }
          - { label: "Conteúdo da Página", name: "body", widget: "markdown" }

  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título do Artigo", name: "title", widget: "string" }
      - { label: "Descrição (SEO)", name: "description", widget: "string" }
      - { label: "Conteúdo do Artigo", name: "body", widget: "markdown" }

  - name: "risotos"
    label: "Receitas - Risotos"
    folder: "receitas/risotos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título da Receita", name: "title", widget: "string" }
      - { label: "Descrição (SEO)", name: "description", widget: "string" }
      - { label: "Conteúdo da Página da Receita", name: "body", widget: "markdown" }

  - name: "sopas"
    label: "Receitas - Sopas Funcionais"
    folder: "receitas/sopas-funcionais"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título da Sopa", name: "title", widget: "string" }
      - { label: "Descrição (SEO)", name: "description", widget: "string" }
      - { label: "Conteúdo da Página da Sopa", name: "body", widget: "markdown" }

  - name: "refeicoes"
    label: "Receitas - Refeições Integrais"
    folder: "receitas/refeicoes-integrais"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título da Refeição", name: "title", widget: "string" }
      - { label: "Descrição (SEO)", name: "description", widget: "string" }
      - { label: "Conteúdo da Página da Refeição", name: "body", widget: "markdown" }

  - name: "emporio"
    label: "Receitas - Empório da Chef"
    folder: "receitas/emporio-da-chef"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título do Produto", name: "title", widget: "string" }
      - { label: "Descrição (SEO)", name: "description", widget: "string" }
      - { label: "Conteúdo da Página do Produto", name: "body", widget: "markdown" }

  - name: "bairros"
    label: "Páginas de Bairros"
    folder: "onde-encontrar"
    create: false
    fields:
      - { label: "Título da Página (SEO)", name: "title", widget: "string" }
      - { label: "Descrição (SEO)", name: "description", widget: "string" }
      - { label: "Conteúdo da Página", name: "body", widget: "markdown" }
