# ===================================================================
# PAINEL DE COMANDO v3.0 - REVISTA DIGITAL CHEFBRICO
# Arquiteto de Conteúdo para a Chef Maria Conceição
# ===================================================================

# --- Conexão Segura com o Repositório ---
# Utiliza o sistema da Netlify para autenticação e acesso ao GitHub.
backend:
  name: git-gateway
  branch: desenvolvimento # O branch de trabalho principal do projeto.

# --- Gestão de Mídia ---
# Define onde as imagens e ficheiros enviados pelo painel serão guardados.
media_folder: "imagens/uploads"
public_folder: "/imagens/uploads"

# --- Interface e Fluxo de Trabalho ---
# Traduz a interface e habilita um fluxo de revisão de conteúdo.
locale: 'pt'
publish_mode: editorial_workflow

# ===================================================================
# COLEÇÕES DE CONTEÚDO (O Coração do Painel)
# Mapeamento direto da arquitetura do site.
# ===================================================================
collections:

  # --- Coleção Principal: O Cardápio ---
  CONFIGURAÇÃO VALIDADA CONFORME NOVA DIRETRIZ
- name: "receitas"
  label: "🍳 Receitas"
  folder: "receitas" # <-- CORRETO
  create: true
  slug: "{{slug}}"
  path: "{{folder}}/{{category}}/{{slug}}"
    # Estratégia de caminho: Salva o ficheiro na subpasta correta baseado na categoria!
    path: "{{folder}}/{{category}}/{{slug}}"
    summary: "{{title}} | Categoria: {{category}}"
    fields:
      - { label: "Nome do Prato", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime" }
      - { label: "Categoria do Prato", name: "category", widget: "select", options: ["risotos", "solucoes", "sopas-funcionais", "refeicoes-integrais"] }
      - { label: "Imagem de Destaque", name: "image", widget: "image" }
      - { label: "Resumo (para SEO e prévias)", name: "summary", widget: "text" }
      - { label: "Conteúdo Principal (Modo de Preparo, etc.)", name: "body", widget: "markdown" }
      # Campos Adicionais para Schema.org (SEO Avançado)
      - label: "Detalhes para SEO (Google Rich Results)"
        name: "recipe_details"
        widget: "object"
        fields:
          - { label: "Serve (Nº de Pessoas)", name: "servings", widget: "number", min: 1, default: 2 }
          - { label: "Tempo de Preparo (Ex: 30M)", name: "prepTime", widget: "string", hint: "Formato: 15M para 15 minutos, 1H para 1 hora, 1H30M para 1h30m." }
          - { label: "Tempo de Cozimento (Ex: 45M)", name: "cookTime", widget: "string" }

  # --- Coleção para o Blog (Autoridade E-E-A-T) ---
  - name: "blog"
    label: "✍️ Blog"
    label_singular: "Novo Artigo"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    path: "{{folder}}/{{slug}}/index" # Cria cada post numa subpasta com um index
    summary: "{{title}} | {{date}}"
    fields:
      - { label: "Título do Artigo", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime" }
      - { label: "Autor", name: "author", widget: "string", default: "Chef Maria Conceição" }
      - { label: "Imagem de Destaque", name: "image", widget: "image" }
      - { label: "Resumo do Artigo", name: "summary", widget: "text" }
      - { label: "Conteúdo Principal", name: "body", widget: "markdown" }

  # --- Coleção para SEO Local ---
  - name: "locais"
    label: "📍 Onde Encontrar (SEO Local)"
    label_singular: "Novo Bairro/Local"
    folder: "onde-encontrar"
    create: true
    slug: "{{slug}}"
    summary: "{{title}}"
    fields:
      - { label: "Nome da Região/Bairro", name: "title", widget: "string" }
      - { label: "Conteúdo da Página", name: "body", widget: "markdown", hint: "Descreva os parceiros, pontos de venda ou a relação da ChefBrico com esta localidade." }
